# NBA Stat Predictor Configuration
# This file contains all configurable parameters for easy customization

# Database settings
database:
  path: "data/nba_data.db"
  backup_enabled: true
  backup_retention_days: 30

# Data collection settings
data_collection:
  default_players_limit: 100  # Increased for better coverage
  max_players_limit: 300      # Increased for comprehensive data
  seasons_to_collect: ["2024-25", "2023-24", "2022-23", "2021-22", "2020-21", "2019-20", "2018-19", "2017-18"]
  min_games_per_player: 20    # Increased for more reliable models
  api_delay_seconds: 0.6
  max_retries: 5              # Increased for reliability
  # Enhanced data collection settings
  include_playoffs: true      # Include playoff data for better patterns
  include_all_star: false     # Exclude all-star games (different intensity)
  min_seasons_per_player: 2   # Require multiple seasons for better patterns
  max_historical_years: 8     # Go back 8 years for comprehensive history

# Model training settings
models:
  algorithms:
    - ensemble        # Primary model with stacking
    - lightgbm       # Advanced gradient boosting
    - catboost       # Categorical boosting
    - random_forest  # Robust baseline
    - xgboost        # Extreme gradient boosting
    - neural_network # Deep learning approach
  
  # Default model for new training
  default_algorithm: ensemble
  
  # Advanced hyperparameter optimization
  hyperparameter_optimization:
    enabled: true
    n_iterations: 50  # Increased for better optimization
    cv_folds: 5
    early_stopping: true
    patience: 10
    
  # Model-specific configurations
  random_forest:
    n_estimators: 150
    max_depth: 12
    min_samples_split: 3
    min_samples_leaf: 1
    random_state: 42
    
  lightgbm:
    num_leaves: 31
    learning_rate: 0.05
    feature_fraction: 0.9
    bagging_fraction: 0.8
    min_child_samples: 20
    random_state: 42
    
  catboost:
    iterations: 1000
    learning_rate: 0.03
    depth: 6
    l2_leaf_reg: 3
    random_seed: 42
    
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    
  neural_network:
    hidden_layer_sizes: [100, 50, 25]
    learning_rate_init: 0.001
    max_iter: 1000
    random_state: 42
    
  validation:
    test_size: 0.15  # Reduced for more training data
    cv_folds: 5
    time_series_cv: true  # Use time series cross-validation
    # Enhanced validation settings
    temporal_split: true    # Ensure temporal ordering
    min_train_size: 1000    # Minimum training samples
    validation_strategy: "time_series"  # Use time series validation
    
  retraining:
    performance_threshold: 0.10  # Retrain if MAE increases by 10%
    min_days_between_retraining: 5
    auto_retrain: true
    
# Prediction settings
predictions:
  stats_to_predict: ["pts", "reb", "ast", "stl", "blk"]
  confidence_threshold: 0.6
  max_predictions_per_stat: 20
  
# Advanced feature engineering settings
features:
  rolling_windows: [3, 5, 10, 15, 20, 25, 30]  # Extended windows for better patterns
  trend_periods: [3, 5, 10, 15, 20, 25]         # Extended trend analysis
  home_away_splits: true
  rest_analysis: true
  consistency_metrics: true
  # Enhanced feature settings
  seasonal_patterns: true    # Capture seasonal trends
  career_progression: true   # Track career development
  injury_impact: true        # Account for injury history
  team_changes: true         # Track team changes impact
  
  # Advanced feature sets
  opponent_strength: true
  head_to_head_analysis: true
  situational_features: true
  momentum_features: true
  clutch_performance: true
  pace_adjusted_stats: true
  usage_patterns: true
  
  # Feature processing
  outlier_detection: true
  feature_scaling: true
  missing_value_strategy: "median"  # median, mean, or zero
  
  # Lookback periods
  default_lookback_games: 30  # Increased for better context
  max_lookback_games: 60      # Increased for comprehensive analysis
  # Enhanced lookback settings
  adaptive_lookback: true      # Adjust based on player age/experience
  minimum_lookback: 15         # Minimum games for analysis
  
# Logging settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file_enabled: true
  file_path: "logs/nba_predictor.log"
  max_file_size_mb: 10
  backup_count: 5
  
# Performance monitoring
monitoring:
  accuracy_window_days: 14
  performance_alerts: true
  email_notifications: false  # Future feature
  
# API settings (for future web interface)
api:
  enabled: false
  host: "localhost"
  port: 8000
  
# Visualization settings
visualization:
  save_plots: true
  plot_directory: "plots"
  figure_size: [12, 8]
  style: "seaborn-v0_8" 